/**********************************************************************/
/****************** Carlos Palacios Alonso 1º DAW *********************/
/**********************************************************************/

/*************************** Ejemplos *********************************/ 

SELECT SYSDATE FROM DUAL;

SELECT FECHA_ALT, ADD_MONTHS(FECHA_ALT,12)  FROM EMPLE;

SELECT FECHA_ALT, LAST_DAY(FECHA_ALT) 	    FROM EMPLE;

SELECT MONTHS_BETWEEN(SYSDATE,'01/01/2019') FROM DUAL;

SELECT ROUND(MONTHS_BETWEEN(SYSDATE,'01/01/2019')) FROM DUAL;

SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,'01/01/2019')) FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'LUNES') 				   FROM DUAL;

SELECT TO_CHAR(FECHA_ALT, 'Month DD, YYYY') "Fecha Alta" FROM EMPLE;

SELECT TO_CHAR(FECHA_ALT, 'Mon ddd y yy y') "Fecha Alta" FROM EMPLE;

ALTER SESSION SET NLS_DATE_LANGUAGE=French;

SELECT TO_CHAR(FECHA_ALT, 'Month DD, YYYY') "Fecha Alta" FROM EMPLE;

ALTER SESSION SET NLS_DATE_LANGUAGE=Spanish;

/* Según los apuntes debería funcionar, pero a mi no me modifica nada */
ALTER SESSION SET NLS_DATE_FORMAT='DD/month/YYY HH24:MI:SS';  

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(010,'999'), TO_CHAR(-101,'999'), 
	   TO_CHAR(001,'999'), TO_CHAR(00,'999'), 
	   TO_CHAR(1000,'999') 					  		FROM DUAL;
	   
SELECT TO_CHAR(-10,'0999'), TO_CHAR(-10,'9990'), 
	   TO_CHAR(0,'9990'), 	TO_CHAR(0,'0999') 	 	FROM DUAL;

SELECT TO_CHAR(10,'$9999'), TO_CHAR(10,'$0999'), 
	   TO_CHAR(0,'$099'), 	TO_CHAR(0,'$009') 	 	FROM DUAL;

SELECT TO_CHAR(0,'B999'),  TO_CHAR(050,'B999')   	FROM DUAL;

SELECT TO_CHAR(-55,'999'), TO_CHAR(-55,'999MI')  	FROM DUAL;

SELECT TO_CHAR(55,'S999'), TO_CHAR(55,'999S'), 
	   TO_CHAR(-55,'S999'), TO_CHAR(-55,'999S')  	FROM DUAL;

SELECT TO_CHAR(-55,'999PR'), TO_CHAR(55,'999PR') 	FROM DUAL;

SELECT TO_CHAR(34.255,'99D99'), TO_CHAR(34,'99D99'), 
	   TO_CHAR(34,'999D999') 					 	FROM DUAL;

SELECT TO_CHAR(1234,'9G999'), TO_CHAR(12340,'9G999'), 
	   TO_CHAR(124,'9G999'), TO_CHAR(0234,'9G999')  FROM DUAL;

SELECT TO_CHAR(123,'C999'), TO_CHAR(123,'999C'), 
	   TO_CHAR(123,'9C99') 						    FROM DUAL;

SELECT TO_CHAR(123,'L999'), TO_CHAR(123,'9L99'), 
	   TO_CHAR(123,'999L') 						    FROM DUAL;

SELECT TO_CHAR(1234,'9,999'), TO_CHAR(1234,'99,99') FROM DUAL;

SELECT TO_CHAR(1,'9.999'), TO_CHAR(12,'99.9') 		FROM DUAL;

SELECT TO_CHAR(123.45,'999V99'), TO_CHAR(123,'999V99') FROM DUAL;

SELECT TO_CHAR(12345,'9.9EEEE'), TO_CHAR(12345,'9EEEE'),
	   TO_CHAR(12345,'9.99EEEE') 					   FROM DUAL;

SELECT TO_CHAR(123,'RN'), TO_CHAR(123,'rn') 		   FROM DUAL;

SELECT TO_CHAR(12.8,'FM99.9'),TO_CHAR(12,'FM99'), 
	   TO_CHAR(-12,'FM99') 						  	   FROM DUAL;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS='/*';

SELECT TO_CHAR(12345.67,'999G999D999') 		  		   FROM DUAL;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS=',.';

ALTER SESSION SET NLS_CURRENCY='PESETAS';

SELECT TO_CHAR(123,'L999') 				 	  		   FROM DUAL;

ALTER SESSION SET NLS_ISO_CURRENCY=AMERICA;

SELECT TO_CHAR(123,'C999') 				   			   FROM DUAL;

SELECT TO_NUMBER ('-123456') "NUMER01", TO_NUMBER ('123,99','999D99') "NUMER02" FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

SELECT TO_DATE('01022000') 					   	  					  			FROM DUAL;

SELECT TO_CHAR(TO_DATE('01010001','ddmmyyyy'),'MONTH') 							FROM DUAL;

SELECT APELLIDO, OFICIO, DECODE(UPPER(OFICIO), 
	   			 		 'PRESIDENTE', 1, 
						 'EMPLEADO', 2,
						 9) "COD" 
FROM EMPLE;

SELECT APELLIDO, VSIZE(APELLIDO) "TAMAÑO" FROM EMPLE;

SELECT USER,UID  				 		  FROM DUAL;

SELECT APELLIDO, DUMP(APELLIDO,17,1,2), 
	   DUMP(APELLIDO,17), DUMP(APELLIDO,17,2,2) 	FROM EMPLE;
	   
	   
/********************************** Ejercicios Prácticos ************************************/
/* Ejercicio 7 */

SELECT SYSDATE FROM DUAL;

SELECT FECHA_ALT, ADD_MONTHS(FECHA_ALT,12) 	   FROM EMPLE WHERE DEPT_NO=10;

SELECT FECHA_ALT, LAST_DAY(FECHA_ALT) 		   FROM EMPLE WHERE DEPT_NO=10;

SELECT TRUNC (MONTHS_BETWEEN(SYSDATE,'11/03/1999')/12) "Edad actual" FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'JUEVES') "SIG. JUEVES" 	   		 		 FROM DUAL;

/* Ejercicio 8 */

SELECT TO_CHAR(FECHA_ALT, 'month DD, YYYY') "NUEVA FECHA" FROM EMPLE WHERE DEPT_NO=10;

SELECT TO_CHAR(FECHA_ALT, 'mon ddd y yyy') "FECHA" 		  FROM EMPLE WHERE DEPT_NO=10;

/* Ejercicio 9 */

SELECT TO_CHAR(SYSDATE,'"Hoy es " day "," dd " de " month " de " yyyy') "Fecha" FROM DUAL;

/* Ejercicio 10 */

SELECT TO_NUMBER('-123456') "NUMERO 1", TO_NUMBER('123,99','999D99') "NUMERO 2" FROM DUAL;

SELECT TO_NUMBER('123.456','999G999') "NO CONVIERTE" 				 		 	FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

SELECT TO_DATE('01012006') 					   									FROM DUAL;

/* ERROR. No está escrito de forma correcta porque no coincide el formato con el 
formato que le dimos al sysdate, ni esta definido en TO_DATE */
SELECT TO_DATE('010106') 		 		 		  	 		 FROM DUAL;	 

SELECT TO_CHAR(TO_DATE('01012007','ddmmyyyy'),'Month') "MES" FROM DUAL;

/* Ejercicio 11 */

SELECT APELLIDO, OFICIO, DECODE(UPPER(OFICIO), 'PRESIDENTE', 1, 'EMPLEADO', 2, 5) "COD" FROM EMPLE;

SELECT APELLIDO, VSIZE(APELLIDO) "TAMAÑO BYTES" 			 FROM EMPLE WHERE DEPT_NO=10;

SELECT APELLIDO, DUMP(APELLIDO,16,1,1) 	 					 FROM EMPLE WHERE APELLIDO LIKE 'SALA';

SELECT USER, UID FROM DUAL;
