/***** Carlos Palacios Alonso, 1º DAW *****/
/***** ACTIVIDADES COMPLEMENTARIAS 4.5 ****/

/* Ejercicio 1 */
SELECT SUM(SALARIO), OFICIO FROM EMPLE
GROUP BY OFICIO;

/* Ejercicio 2 */
SELECT APELLIDO FROM EMPLE
WHERE SALARIO IN (SELECT AVG(SALARIO) FROM EMPLE GROUP BY DEPT_NO);

/* Ejercicio 3 */
SELECT COUNT(*) FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO

/* Ejercicio 4 */
SELECT DEPT_NO FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO
HAVING COUNT(*)>= ALL (SELECT COUNT(*) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO);

/* Ejercicio 5 */
SELECT E.DEPT_NO, D.DNOMBRE FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO AND E.OFICIO='EMPLEADO'
GROUP BY E.DEPT_NO, DNOMBRE
HAVING COUNT(*)>= ALL 
(SELECT COUNT(*) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO);

/* Ejercicio 6 */
SELECT D.DEPT_NO, D.DNOMBRE FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO
GROUP BY D.DEPT_NO, E.OFICIO, D.DNOMBRE
HAVING COUNT(*)>2

/* Ejercicio 7 */
SELECT NOMBRE FROM ALUM
INTERSECT
(SELECT NOMBRE FROM ANTIGUOS UNION SELECT NOMBRE FROM NUEVOS);

/* Ejercicio 8 */
SELECT NOMBRE FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE FROM ANTIGUOS)
OR NOMBRE IN (SELECT NOMBRE FROM NUEVOS);

SELECT NOMBRE FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE FROM ANTIGUOS UNION SELECT NOMBRE FROM NUEVOS);

SELECT NOMBRE FROM ALUM INTERSECT SELECT NOMBRE FROM ANTIGUOS
UNION
(SELECT NOMBRE FROM ALUM INTERSECT SELECT NOMBRE FROM NUEVOS);

/* Ejercicio 9 */
SELECT NOMBRE FROM ALUM
MINUS
(SELECT NOMBRE FROM ANTIGUOS UNION SELECT NOMBRE FROM NUEVOS);

/* Ejercicio 10 */
SELECT NOMBRE, ESPECIALIDAD, COUNT(*)

/* Ejercicio 11 */

/* Ejercicio 12 */

/* Ejercicio 13 */

/* Ejercicio 14 */

/* Ejercicio 15 */

/* Ejercicio 16 */

