/****************** Carlos Palacios Alonso, 1º DAW ***********************************/
/* 1 CORREGIDO */
SELECT E.APELLIDO, E.OFICIO, D.LOC
FROM DEPART D, EMPLE E
WHERE E.DEPT_NO=D.DEPT_NO AND E.OFICIO='ANALISTA';

/* 2 */
SELECT * FROM EMPLE WHERE DIR=
(SELECT EMP_NO FROM EMPLE WHERE APELLIDO='CEREZO');

/* 3 */
SELECT * FROM EMPLE WHERE DEPT_NO=
(SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS');

/* 4 CORREGIDO */
SELECT * FROM DEPART WHERE DEPT_NO NOT IN 
(SELECT DEPT_NO FROM EMPLE);

/* OTRA FORMA DE RESOLVERLO - MEJOR POR NO HACER SUBCONSULTA */
SELECT * FROM DEPART D WHERE NOT EXISTS (SELECT E.DEPT_NO FROM EMPLE E
	   	 	  		   		 	 		WHERE D.DEPT_NO=E.DEPT_NO)

/* 5 CORREGIDO */
SELECT * FROM DEPART WHERE DEPT_NO IN 
(SELECT DEPT_NO FROM EMPLE);

/* OTRA FORMA DE RESOLVERLO - MEJOR POR NO HACER SUBCONSULTA */
SELECT D.DEPT_NO, DNOMBRE, LOC 
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO=E.DEPT_NO
GROUP BY D.DEPT_NO, DNOMBRE, LOC

/* 6 */
SELECT APELLIDO, SALARIO FROM EMPLE WHERE SALARIO>
ALL (SELECT SALARIO FROM EMPLE WHERE DEPT_NO=20);

/* 7 */
SELECT TEMA, ESTANTE, EJEMPLARES FROM LIBRERIA 
WHERE EJEMPLARES BETWEEN 8 AND 15;
	  
/* 8 */
SELECT TEMA, ESTANTE, EJEMPLARES FROM LIBRERIA 
WHERE ESTANTE NOT BETWEEN 'B' AND 'D';

/* 9 */
SELECT TEMA FROM LIBRERIA 
WHERE EJEMPLARES < ALL (SELECT EJEMPLARES 
FROM LIBRERIA WHERE TEMA='MEDICINA');

/* 10 */
SELECT TEMA FROM LIBRERIA WHERE EJEMPLARES NOT BETWEEN 15 AND 20;

/* 11 */
SELECT NOMBRE FROM ASIGNATURAS ASIG, NOTAS N, ALUMNOS A
WHERE ASIG.COD=N.COD AND N.DNI=A.DNI 
AND ASIG.NOMBRE LIKE '%o%o%o%' AND A.POBLA='Madrid';

/* 12 */
SELECT APENOM FROM NOTAS N, ALUMNOS A
WHERE N.DNI=A.DNI AND
NOTA<5 AND POBLA='Madrid';

/* 13  CORREGIDO [FALTABA QUITAR CUANDO ES FOL] */
SELECT APENOM, NOTA FROM NOTAS N, ALUMNOS A, ASIGNATURAS AG
WHERE A.DNI=N.DNI AND N.COD=AG.COD AND NOTA=(SELECT NOTA 
	  			  	  		FROM ASIGNATURAS ASIG, ALUMNOS A, NOTAS N 
	  			  	  		WHERE NOMBRE='FOL' AND APENOM='Díaz Fernández, María' 
							AND ASIG.COD=N.COD AND A.DNI=N.DNI)
AND (APENOM!='Díaz Fernández, María' OR NOMBRE!='FOL');

/* 14 */
SELECT * FROM ASIGNATURAS WHERE COD NOT IN 
(SELECT COD FROM NOTAS);

/* 15 */
SELECT A.APENOM FROM ALUMNOS A, NOTAS N 
WHERE A.DNI=N.DNI AND N.COD=1;

/* 16 */
SELECT APENOM FROM ALUMNOS WHERE DNI NOT IN 
(SELECT DNI FROM NOTAS WHERE COD=1);