/***** Carlos Palacios Alonso, 1º DAW *****/
/***** ACTIVIDADES COMPLEMENTARIAS 4.5 ****/

/* Ejercicio 1 */
SELECT SUM(SALARIO), OFICIO FROM EMPLE
GROUP BY OFICIO;

/* Ejercicio 2 */
SELECT APELLIDO FROM EMPLE
WHERE SALARIO IN (SELECT AVG(SALARIO) 
	  		  	 FROM EMPLE 
				 GROUP BY DEPT_NO);

/* Ejercicio 3 - CORREGIDO */
SELECT COUNT(*) "Nº EMPLE", DEPT_NO FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO
ORDER BY DEPT_NO

/* Ejercicio 4 - CORREGIDO*/
SELECT DEPT_NO, COUNT(*) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO
HAVING COUNT(*)>= ALL (SELECT COUNT(*) 
	   			  FROM EMPLE 
				  WHERE OFICIO='EMPLEADO' 
				  GROUP BY DEPT_NO);
				  
/* OTRA FORMA SERÍA PONER MAX(COUNT(*)) EN VEZ DE COUNT(*) */

/* Ejercicio 5 CORREGIDO - IGUAL QUE EL ANTERIOR PERO CON UN DATO MÁS A MOSTRAR */
SELECT E.DEPT_NO, D.DNOMBRE, COUNT(*) FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO AND E.OFICIO='EMPLEADO'
GROUP BY E.DEPT_NO, DNOMBRE
HAVING COUNT(*)= (SELECT MAX(COUNT(*))
	   			  FROM EMPLE 
				  WHERE OFICIO='EMPLEADO' 
				  GROUP BY DEPT_NO);

/* Ejercicio 6 CORREGIDO */
SELECT D.DEPT_NO, D.DNOMBRE, E.OFICIO, COUNT(*) FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO
GROUP BY D.DEPT_NO, E.OFICIO, D.DNOMBRE
HAVING COUNT(*)>2

/* Ejercicio 7 - CORREGIDO */

/* QUE ESTEN EN CUALQUIERA DE LAS DOS */
SELECT NOMBRE FROM ALUM
INTERSECT
(SELECT NOMBRE FROM ANTIGUOS UNION SELECT NOMBRE FROM NUEVOS);

/* QUE ESTEN EN AMBAS A LA VEZ */
SELECT NOMBRE FROM ALUM
INTERSECT
SELECT NOMBRE FROM ANTIGUOS 
INTERSECT 
SELECT NOMBRE FROM NUEVOS;

/* Ejercicio 8 */
SELECT NOMBRE FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE FROM ANTIGUOS)
OR NOMBRE IN (SELECT NOMBRE 
   		  	 FROM NUEVOS);

SELECT NOMBRE FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE 
	  		 	FROM ANTIGUOS 
				UNION 
				SELECT NOMBRE 
				FROM NUEVOS);

SELECT NOMBRE FROM ALUM INTERSECT SELECT NOMBRE FROM ANTIGUOS
UNION
(SELECT NOMBRE FROM ALUM INTERSECT SELECT NOMBRE FROM NUEVOS);

/* Ejercicio 9 */
SELECT NOMBRE FROM ALUM
MINUS
(SELECT NOMBRE FROM ANTIGUOS UNION SELECT NOMBRE FROM NUEVOS);

/* Ejercicio 10 - CORREGIDO */
SELECT C.NOMBRE, P.ESPECIALIDAD, COUNT(P.COD_CENTRO) "Nº PROF" FROM CENTROS C, PROFESORES P
WHERE P.COD_CENTRO(+)=C.COD_CENTRO
GROUP BY C.NOMBRE, P.ESPECIALIDAD
ORDER BY C.NOMBRE;

/* OTRA FORMA */
SELECT C.NOMBRE, P.ESPECIALIDAD, COUNT(P.COD_CENTRO) AS "Nº PROF" 
FROM CENTROS C LEFT JOIN PROFESORES P
ON P.COD_CENTRO=C.COD_CENTRO
GROUP BY C.NOMBRE, P.ESPECIALIDAD
ORDER BY C.NOMBRE;

/* Ejercicio 11 */
SELECT C.COD_CENTRO, C.NOMBRE, COUNT(P.COD_CENTRO) "Nº EMP" FROM PERSONAL P, CENTROS C
WHERE P.COD_CENTRO(+)=C.COD_CENTRO
GROUP BY C.COD_CENTRO, C.NOMBRE
ORDER BY C.COD_CENTRO;

/* Ejercicio 12 - CORREGIDO */
SELECT ESPECIALIDAD, COUNT(*) "Nº PROF" FROM PROFESORES
GROUP BY ESPECIALIDAD
HAVING COUNT(*)<= ALL (SELECT COUNT(*) 
	   			  	  FROM PROFESORES 
					  GROUP BY ESPECIALIDAD);
/* OTRA FORMA */
SELECT ESPECIALIDAD, COUNT(*) "Nº PROF" FROM PROFESORES
GROUP BY ESPECIALIDAD
HAVING COUNT(*)= (SELECT MIN(COUNT(*)) 
	   			  	  FROM PROFESORES 
					  GROUP BY ESPECIALIDAD);

/* Ejercicio 13 - CORREGIDO */
SELECT NOMBRE_BANC "Nombre Banco", COUNT(S.COD_SUCUR) "Nº Sucursales" 
FROM BANCOS B, SUCURSALES S
WHERE B.COD_BANCO=S.COD_BANCO
GROUP BY NOMBRE_BANC
HAVING COUNT(S.COD_SUCUR)>= ALL (SELECT COUNT(*) 
	   							FROM SUCURSALES 
								GROUP BY COD_BANCO);

/* Ejercicio 14 */
SELECT NOMBRE_BANC "Nombre Banco", SUM(C.SALDO_DEBE) "Saldo Debe", SUM(SALDO_HABER) "Saldo Haber" 
FROM BANCOS B, CUENTAS C
WHERE B.COD_BANCO=C.COD_BANCO AND POBLACION='GUADALAJARA'
GROUP BY NOMBRE_BANC;

/* Ejercicio 15 - CORREGIDO */
SELECT NOMBRE_CTA "Nombre Cta", COUNT(*) "Nº Movimiento" FROM CUENTAS C, MOVIMIENTOS M
WHERE C.COD_BANCO=M.COD_BANCO AND C.COD_SUCUR=M.COD_SUCUR AND C.NUM_CTA=M.NUM_CTA
GROUP BY NOMBRE_CTA
HAVING COUNT(*)>=ALL (SELECT COUNT(*) 
	   				 FROM MOVIMIENTOS 
					 GROUP BY NUM_CTA);
					 
/* OTRA FORMA */
SELECT NOMBRE_CTA "Nombre Cta", COUNT(*) "Nº Movimiento" FROM CUENTAS C, MOVIMIENTOS M
WHERE C.COD_BANCO=M.COD_BANCO AND C.COD_SUCUR=M.COD_SUCUR AND C.NUM_CTA=M.NUM_CTA
GROUP BY NOMBRE_CTA
HAVING COUNT(*)= (SELECT MAX(COUNT(*)) 
	   				 FROM MOVIMIENTOS 
					 GROUP BY NUM_CTA);


/* Ejercicio 16 */
SELECT NOMBRE_SUC "Nombre Sucursal", COUNT(TIPO_MOV) "Suma Reintegros"
FROM SUCURSALES S, MOVIMIENTOS M
WHERE S.COD_BANCO=M.COD_BANCO AND S.COD_SUCUR=M.COD_SUCUR AND TIPO_MOV='R'
GROUP BY NOMBRE_SUC 
HAVING COUNT(TIPO_MOV)>=ALL (SELECT COUNT(TIPO_MOV) 
	   						FROM MOVIMIENTOS 
							WHERE TIPO_MOV='R' 
							GROUP BY COD_SUCUR);
