/*****************************************************/
/*********** Carlos Palacios Alonso 1º DAW ***********/
/*****************************************************/

/* Ejercicio 1 */
SELECT COD_EMPL, NOM_EMPL
FROM EMPLEADOS E, PROYECTOS P
WHERE E.COD_PROY=P.COD_PROY;

/* Ejercicio 2 */
SELECT COD_PROY, NOM_PROJ FROM PROYECTOS P
WHERE PRECIO > (SELECT SUM(SUELDO) 
	  		   FROM EMPLEADOS E
			   WHERE E.COD_PROY=P.COD_PROY
			   GROUP BY COD_PROY)


/* Ejercicio 3 */
SELECT NOM_DPT, CUIDAD_DPT FROM EMPLEADOS
WHERE COD_PROY IN (3,4)
GROUP BY NOM_DPT, CUIDAD_DPT

/* Ejercicio 4 */
SELECT COD_EMPL, NOM_EMPL 
FROM EMPLEADOS
WHERE SUELDO BETWEEN 5000 AND 8000;

/* Ejercicio 5 */
SELECT D.NOM_DPT, D.CUIDAD_DPT, D.TELEFON 
FROM DEPARTAMENTOS D, EMPLEADOS E
WHERE D.NOM_DPT=E.NOM_DPT AND D.CUIDAD_DPT=E.CUIDAD_DPT
AND E.COD_PROY=(SELECT COD_PROY 
				FROM PROYECTOS 
				WHERE NOM_PROJ='ITACA')
GROUP BY D.NOM_DPT, D.CUIDAD_DPT, D.TELEFON;

/* Ejercicio 6 - CORREGIDO */
SELECT COD_EMPL, NOM_EMPL, APELL_EMPL 
FROM EMPLEADOS E, PROYECTOS P
WHERE E.COD_PROY=P.COD_PROY AND P.PRECIO=(SELECT MAX(PRECIO) 
	  									 FROM PROYECTOS);

/* Ejercicio 7 - CORREGIDO */
SELECT E.NOM_DPT, E.CUIDAD_DPT, SUELDO 
FROM EMPLEADOS E, DEPARTAMENTOS D
WHERE E.NOM_DPT=D.NOM_DPT AND E.CUIDAD_DPT=D.CUIDAD_DPT
GROUP BY E.NOM_DPT, E.CUIDAD_DPT, SUELDO
HAVING SUELDO= ANY (SELECT MAX(SUELDO) 
	   		   	   FROM EMPLEADOS 
				   GROUP BY NOM_DPT, CUIDAD_DPT);
				   
/* OTRA FORMA */
SELECT NOM_DPT, CUIDAD_DPT, SUELDO FROM EMPLEADOS
GROUP BY NOM_DPT, CUIDAD_DPT, SUELDO
HAVING SUELDO= ANY (SELECT MAX(SUELDO) FROM EMPLEADOS
	   		   	   GROUP BY NOM_DPT, CUIDAD_DPT);
				   
/* Ejercicio 8 */
SELECT C.COD_CLI, NOM_CLI 
FROM CLIENTES C, PROYECTOS P
WHERE C.COD_CLI=P.COD_CLI
GROUP BY C.COD_CLI, NOM_CLI
HAVING COUNT(P.COD_CLI)>1;

/* Ejercicio 9 - CORREGIDO */
SELECT P.COD_PROY, NOM_PROJ, SUM(E.SUELDO)
FROM PROYECTOS P, EMPLEADOS E
WHERE E.COD_PROY=P.COD_PROY
GROUP BY P.COD_PROY, NOM_PROJ
HAVING SUM(SUELDO)>30000;

/* Ejercicio 10 - CORREGIDO */
SELECT NOM_DPT, CUIDAD_DPT FROM DEPARTAMENTOS D
WHERE NOT EXISTS (SELECT * FROM EMPLEADOS E 
	  	  		 WHERE E.NOM_DPT=D.NOM_DPT 
				 AND E.CUIDAD_DPT=D.CUIDAD_DPT)
ORDER BY NOM_DPT;

/* OTRA FORMA */
SELECT NOM_DPT, CUIDAD_DPT FROM DEPARTAMENTOS D
WHERE NOM_DPT NOT IN(SELECT NOM_DPT 
	  		  	    FROM EMPLEADOS)
OR CUIDAD_DPT NOT IN(SELECT CUIDAD_DPT 
   			  	  	FROM EMPLEADOS)
ORDER BY NOM_DPT