-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 13:21:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectoTiendaRopa_carlosp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyectoTiendaRopa_carlosp` ;

-- -----------------------------------------------------
-- Schema proyectoTiendaRopa_carlosp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectoTiendaRopa_carlosp` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `proyectoTiendaRopa_carlosp` ;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Proveedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Proveedor` (
  `id_proveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Producto` (
  `id_producto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `talla` VARCHAR(5) NOT NULL,
  `precioOriginal` DOUBLE UNSIGNED NOT NULL,
  `pvp` DOUBLE UNSIGNED NOT NULL,
  `cantidad` INT(100) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `Proveedor_id_proveedor` INT UNSIGNED NOT NULL,
  `fecha_proveedor` DATETIME NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_id_proveedor`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Usuario` (
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `tipo` ENUM("admin", "normal", "transportista", "master") NOT NULL,
  `tlf` VARCHAR(9) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `tlf_UNIQUE` (`tlf` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Transportista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Transportista` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Transportista` (
  `id_transportista` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_transportista`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Pedido` (
  `num_pedido` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_email` VARCHAR(45) NOT NULL,
  `Producto_id_producto` INT UNSIGNED NOT NULL,
  `fecha_compra` DATETIME NOT NULL,
  `precio_final` DOUBLE NOT NULL,
  `Transportista_id_transportista` INT UNSIGNED NOT NULL,
  `fecha_entrega` DATETIME NULL,
  `destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_pedido`),
  INDEX `fk_Usuarios_has_Producto_Producto1_idx` (`Producto_id_producto` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Producto_Usuarios_idx` (`Usuarios_email` ASC) VISIBLE,
  INDEX `fk_Pedido_Transportista1_idx` (`Transportista_id_transportista` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Producto_Usuarios`
    FOREIGN KEY (`Usuarios_email`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id_producto`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Transportista1`
    FOREIGN KEY (`Transportista_id_transportista`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Transportista` (`id_transportista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proyectoTiendaRopa_carlosp`.`Consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoTiendaRopa_carlosp`.`Consultas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proyectoTiendaRopa_carlosp`.`Consultas` (
  `num_consulta` INT NOT NULL AUTO_INCREMENT,
  `Usuario_email` VARCHAR(45) NOT NULL,
  `Producto_id_producto` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`num_consulta`),
  INDEX `fk_Usuarios_has_Producto_Producto2_idx` (`Producto_id_producto` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Producto_Usuarios1_idx` (`Usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Producto_Usuarios1`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Producto_Producto2`
    FOREIGN KEY (`Producto_id_producto`)
    REFERENCES `proyectoTiendaRopa_carlosp`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
